[package]
name = "rust-browser"
version = "0.1.0"
authors = ["inokawa <48897392+inokawa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
image = "0.23.12"
